name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2.1.0
      with:
        platforms: all
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2.2.1

    - name: Build all images
      run: ./build --os=ubuntu --flavor=bionic --host=all -file=Dockerfile.depends --url=https://github.com/dogecoin/dogecoin --commit=1.14.7-dev
