name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        name:
            - armhf-linux
            - aarch64-linux
            - x86_64-linux
            - x86_64-macos
            - x86_64-win
            - i686-win
            - i686-linux
        include:
          - name: armhf-linux
            host: arm-linux-gnueabihf
          - name: aarch64-linux
            host: aarch64-linux-gnu
          - name: x86_64-linux
            host: x86_64-pc-linux-gnu
          - name: i686-linux
            host: i686-pc-linux-gnu
          - name: x86_64-macos
            host: x86_64-apple-darwin11
          - name: x86_64-win
            host: x86_64-w64-mingw32
          - name: i686-win
            host: i686-w64-mingw32

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2.1.0
      with:
        platforms: all
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2.2.1

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build ${{ matrix.host }} and push to Docker Hub
      run: ./build --host=${{ matrix.host }}
