name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        name:
            - armhf-linux
            - aarch64-linux
            - x86_64-linux-dbg
            - x86_64-macos
            - x86_64-win
            - i686-win
            - i686-linux
        include:
          - host: arm-linux-gnueabihf
          - host: aarch64-linux-gnu
          - host: x86_64-pc-linux-gnu
          - host: i686-pc-linux-gnu
          - host: x86_64-apple-darwin11
          - host: x86_64-w64-mingw32
          - host: i686-w64-mingw32

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2.2.1

    - name: Build image for ${{ matrix.host }}
      run: |
        ./build --os=ubuntu --flavor=bionic --host=${{ matrix.host }} -file=Dockerfile.depends --url=https://github.com/dogecoin/dogecoin --commit=1.14.7-dev
